# Generated by Django 6.0.1 on 2026-02-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_customuser_allocation_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
